name: Tag and Publish to npm

on:
  push:
    branches:
      - master

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get latest tag
        id: get_tag
        run: |
          git fetch --tags
          TAG=$(git tag --sort=-v:refname | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | head -n 1)
          echo "latest=$TAG" >> $GITHUB_OUTPUT

      - name: Bump patch version and create tag
        id: bump_tag
        run: |
          old=${{ steps.get_tag.outputs.latest }}
          echo "Old tag: $old"
          if [ -z "$old" ]; then
            old="v1.0.0"
          fi
          version=${old#v}
          IFS='.' read -r major minor patch <<< "$version"
          patch=$((patch + 1))
          new="v$major.$minor.$patch"
          echo "new_tag=$new" >> $GITHUB_OUTPUT
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag $new
          git push origin $new

      - name: Output new tag
        run: 'echo "🚀 New tag created: ${{ steps.bump_tag.outputs.new_tag }}"'

  publish:
    runs-on: ubuntu-latest
    needs: tag
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm install

      - name: Build package
        run: npm run build

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
